### ISSUE TITLE
Do not succeed to connect with npx @inrupt/generate-oidc-token 

### ISSUE THREAD

**Issue by bourgeoa** [o-development/clone-to-solid-pod#2]
I made : 
- npx @inrupt/generate-oidc-token
- select : ` https://broker.pod.inrupt.com`
- 
```
These are your login credentials:
{
  "refreshToken" : "liu9bVk_dBZw4I_ufo7_mCYx-wPiwCF-wY4CCXbOBCs",
  "clientId"     : "2a2h5J1Jqtq-URRT7lb31Q9LR2wZbogylnweDmyeJhk",
  "clientSecret" : "o-51Vsacc2kXQSIlw6ar2ysMVG4KpLeMLjAocCjNSHc",
  "oidcIssuer"   : "https://broker.pod.inrupt.com/",
}

```
```
root@DESKTOP-PIRJOCS:/mnt/d/github/bourgeoa/clone-to-solid-pod# cat .env

INPUT_REFRESH_TOKEN={liu9bVk_dBZw4I_ufo7_mCYx-wPiwCF-wY4CCXbOBCs}
INPUT_CLIENT_ID={2a2h5J1Jqtq-URRT7lb31Q9LR2wZbogylnweDmyeJhk}
INPUT_CLIENT_SECRET={o-51Vsacc2kXQSIlw6ar2ysMVG4KpLeMLjAocCjNSHc}
INPUT_OIDC_ISSUER=https://solidweb.me

INPUT_TARGET_CONTAINER=https://solidweb.me/bourgeoa/public/
```

```
root@DESKTOP-PIRJOCS:/mnt/d/github/bourgeoa/clone-to-solid-pod# npm run start

> clone-to-solid-pod@0.0.1 start /mnt/d/github/bourgeoa/clone-to-solid-pod
> ts-node lib/index.ts

https://solidweb.me
(node:3797) DraftWarning: The DPoP APIs implements an IETF draft (https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-04.html). Breaking draft implementations are included as minor versions of the openid-client library, therefore, the ~ semver operator should be used and close attention be payed to library changelog as well as the drafts themselves.
(node:3797) UnhandledPromiseRejectionWarning: Error: Invalid refresh credentials: OPError: invalid_client (client authentication failed)
    at refreshAccess (/mnt/d/github/bourgeoa/clone-to-solid-pod/node_modules/@inrupt/solid-client-authn-node/src/login/oidc/oidcHandlers/RefreshTokenOidcHandler.ts:105:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3797) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3797) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jaxoncreed** [comment]
We talked about this in our meeting. I haven't tested this using Inrupt's ESS Identity Broker. To get a different identity provider, you can select the third option in @inrupt/generate-oidc-token
